### ISSUE TITLE
嘶……CTAN上好像痛失网名了呢

### ISSUE THREAD

**Issue by clerkma** [RadioNoiseE/apltex#1]
见[CTAN页面](https://ctan.org/pkg/apltex)。
不过也不是什么大问题。

**Comment by RadioNoiseE** [comment]
还好只是拼音？

**Comment by RadioNoiseE** [comment]
> 还好只是拼音？

艹，然后我看了一下evangelion-jfm的、发现虽然写了RadioNoiseE、但是后面的括号里还是写了拼音

**Comment by clerkma** [comment]
😊
